---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2.0.1

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      # Use dokken-single as we don't support CentOS-6
      # Test default config
      - kitchen/dokken-single:
          name: default
          suite: default
          requires:
            *lint_and_unit

      # source install tests
      - kitchen/dokken-single:
          name: source
          suite: source
          requires:
            *lint_and_unit

      # prebuild tests
      - kitchen/dokken-single:
          name: prebuild
          suite: prebuild
          requires:
            *lint_and_unit
    environment:
      CHEF_LICENSE: "accept-no-persist"
