---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@1.1.2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      # Use dokken-single as we don't support CentOS-6
      # Test default config
      - kitchen/dokken-single:
          name: default-centos-7
          platform: centos-7
          suite: default
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-8
          platform: debian-8
          suite: default
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-9
          platform: debian-9
          suite: default
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-16.04
          platform: ubuntu-1604
          suite: default
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-18.04
          platform: ubuntu-1804
          suite: default
          requires:
            *lint_and_unit

      # source install tests
      - kitchen/dokken-single:
          name: source-centos-7
          platform: centos-7
          suite: source
          requires: [default-centos-7]
      - kitchen/dokken-single:
          name: source-debian-8
          platform: debian-8
          suite: source
          requires: [default-debian-8]
      - kitchen/dokken-single:
          name: source-debian-9
          platform: debian-9
          suite: source
          requires: [default-debian-9]
      - kitchen/dokken-single:
          name: source-ubuntu-16.04
          platform: ubuntu-1604
          suite: source
          requires: [default-ubuntu-16.04]
      - kitchen/dokken-single:
          name: source-ubuntu-18.04
          platform: ubuntu-1804
          suite: source
          requires: [default-ubuntu-18.04]

      # prebuild tests
      - kitchen/dokken-single:
          name: prebuild-centos-7
          platform: centos-7
          suite: prebuild
          requires: [source-centos-7]
      - kitchen/dokken-single:
          name: prebuild-debian-8
          platform: debian-8
          suite: prebuild
          requires: [source-debian-8]
      - kitchen/dokken-single:
          name: prebuild-debian-9
          platform: debian-9
          suite: prebuild
          requires: [source-debian-9]
      - kitchen/dokken-single:
          name: prebuild-ubuntu-16.04
          platform: ubuntu-1604
          suite: prebuild
          requires: [source-ubuntu-16.04]
      - kitchen/dokken-single:
          name: prebuild-ubuntu-18.04
          platform: ubuntu-1804
          suite: prebuild
          requires: [source-ubuntu-18.04]
